name: Commit Request Checker
on:
  push:
    branches:
      - main # TODO: change later to some branch that allows for commits, dont want this to run for every pull request
  pull_request:
    branches:
      - '*'

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r bots/requirements.txt

    - name: Check for if quest is accepted
      id: check_accepted
      run: python bots/Quests.py ${{ github.repository_owner }} check first_commit
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI}}

    - name: Run commit checker
      if: steps.check_quest.check_accepted == 'success'
      run: python bots/CommitChecker.py ${{ github.repository_owner }} ${{ github.repository }} ${{ github.ref_name }}
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI}}
